name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v4
      - name: Install shards
        run: shards install

      - name: Run specs
        run: crystal spec

      - name: Build release binary
        run: shards build --release

      - name: Package artifacts
        run: |
          mkdir -p dist
          cp bin/cr-analyzer dist/cr-analyzer-linux-x64
          cd dist
          sha256sum cr-analyzer-linux-x64 > SHA256SUMS

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
